In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import sklearn
from sklearn.utils import shuffle
# from sklearn.model_selection import train_test_split

%matplotlib inline

df = pd.read_csv("C:/Users/shahh/OneDrive/Desktop/Research Paper - KS/Final CSV/April/final_data.csv")
# df = df.drop(columns=['File Name','Number of cells','Cell Number'])
df = shuffle(df)
df



In [ ]:
df = df.drop(columns=['File Name'])
df

In [ ]:
X = df.drop('IsShade', axis=1)
y = df['IsShade']


In [4]:

from sklearn.model_selection import train_test_split
# implementing train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.34, random_state=44)



In [5]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
# random forest model creation
rfc = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)


In [6]:
print('Train set')
train_pred = rfc.predict_proba(X_train)
print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, train_pred[:,1])))
print('Test set')
test_pred = rfc.predict_proba(X_test)
print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, test_pred[:,1])))

Train set
Random Forests roc-auc: 0.9877283173780718
Test set
Random Forests roc-auc: 0.9870733847506907


In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

rfc_cv_score = cross_val_score(rfc, X, y, cv=10, scoring='roc_auc')

In [20]:
from sklearn.model_selection import KFold
scores_rf = []
kfold = KFold(n_splits=3)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=kfold)))
print(np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.93718252 0.95029533 0.93301831]
0.9401653868871825


In [23]:
from sklearn.model_selection import KFold
scores_rf = []
kfold = KFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=kfold)))
print(np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.93423902 0.95235283 0.93256547 0.93955503 0.93719236 0.94132703
 0.93945659 0.93699547 0.93256547 0.93423902]
0.9380488285095492


In [24]:
from sklearn.model_selection import StratifiedKFold
scores_rf = []
skfold = StratifiedKFold(n_splits=3)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=skfold)))
print(np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.93877732 0.95032487 0.93422918]
0.9380488285095492


In [25]:
from sklearn.model_selection import StratifiedKFold
scores_rf = []
skfold = StratifiedKFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=skfold)))
print(np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.93326115 0.95058569 0.93473767 0.93975785 0.93827525 0.9401457
 0.93698927 0.93846608 0.92606084 0.934331  ]
0.9380488285095492


In [8]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[16141  1129]
 [ 1090 16178]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     17270
           1       0.93      0.94      0.94     17268

    accuracy                           0.94     34538
   macro avg       0.94      0.94      0.94     34538
weighted avg       0.94      0.94      0.94     34538



=== All AUC Scores ===
[0.98725685 0.98991993 0.98825192 0.98919361 0.98860299 0.9875973
 0.98839587 0.98802733 0.98552349 0.98766368]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9880432962093607


In [9]:
from sklearn.metrics import accuracy_score

print("Train Accuracy :: ", accuracy_score(y_train, rfc.predict(X_train)))
print("Test Accuracy  :: ", accuracy_score(y_test, rfc_predict))

Train Accuracy ::  0.9374272843888906
Test Accuracy  ::  0.9357519254154844


In [27]:
from sklearn.svm import SVC
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.8573165788406972

0.9357519254154844